import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import type { Database } from '@/integrations/supabase/types';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/contexts/AuthContext';

type Farmer = Database['public']['Tables']['farmers']['Row'];
type FarmerInsert = Database['public']['Tables']['farmers']['Insert'];
type FarmerUpdate = Database['public']['Tables']['farmers']['Update'];

export interface FarmerWithCenter extends Farmer {
  collection_centers?: {
    name: string;
    code: string;
  } | null;
}

export function useFarmers(centerId?: string) {
  return useQuery({
    queryKey: ['farmers', centerId],
    queryFn: async () => {
      let query = supabase
        .from('farmers')
        .select(`
          *,
          collection_centers (
            name,
            code
          )
        `)
        .order('created_at', { ascending: false });

      if (centerId) {
        query = query.eq('center_id', centerId);
      }

      const { data, error } = await query;

      if (error) throw error;
      return data as FarmerWithCenter[];
    },
  });
}

export function useFarmer(id: string) {
  return useQuery({
    queryKey: ['farmer', id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('farmers')
        .select(`
          *,
          collection_centers (
            name,
            code
          )
        `)
        .eq('id', id)
        .single();

      if (error) throw error;
      return data as FarmerWithCenter;
    },
    enabled: !!id,
  });
}

export function useCreateFarmer() {
  const queryClient = useQueryClient();
  const { toast } = useToast();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async (farmer: Omit<FarmerInsert, 'farmer_code'>) => {
      const { data, error } = await supabase
        .from('farmers')
        .insert({
          ...farmer,
          farmer_code: '', // Will be auto-generated by trigger
          created_by: user?.id || null,
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['farmers'] });
      toast({
        title: 'Farmer Added',
        description: 'The farmer has been successfully registered.',
      });
    },
    onError: (error: Error) => {
      toast({
        title: 'Error',
        description: error.message,
        variant: 'destructive',
      });
    },
  });
}

export function useUpdateFarmer() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, ...updates }: FarmerUpdate & { id: string }) => {
      const { data, error } = await supabase
        .from('farmers')
        .update(updates)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['farmers'] });
      queryClient.invalidateQueries({ queryKey: ['farmer', data.id] });
      toast({
        title: 'Farmer Updated',
        description: 'The farmer details have been updated.',
      });
    },
    onError: (error: Error) => {
      toast({
        title: 'Error',
        description: error.message,
        variant: 'destructive',
      });
    },
  });
}

export function useCollectionCenters() {
  const { user, isAdmin } = useAuth();

  return useQuery({
    queryKey: ['collection-centers', user?.id, isAdmin],
    queryFn: async () => {
      if (!user) return [];

      if (isAdmin) {
        // Admin: fetch all active centers
        const { data, error } = await supabase
          .from('collection_centers')
          .select('*')
          .eq('is_active', true)
          .order('name');

        if (error) throw error;
        return data;
      } else {
        // Staff: fetch only centers they are assigned to
        const { data, error } = await supabase
          .from('user_center_assignments')
          .select(`
            center_id,
            collection_centers (*)
          `)
          .eq('user_id', user.id);

        if (error) throw error;
        
        // Extract the collection centers from the assignments
        const centers = data
          ?.map(assignment => assignment.collection_centers)
          .filter((center): center is NonNullable<typeof center> => 
            center !== null && center.is_active
          );
        
        return centers || [];
      }
    },
    enabled: !!user,
  });
}
